version: "3.8"

services:
  # Backend API
  face-rec-api:
    container_name: backend
    env_file:
      - .env
    build: ./
    command: npm start
    working_dir: /user/src/face-rec-api
    environment:
      - POSTGRES_URI=${URI}
      - REDIS_URI=redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./:/user/src/face-rec-api

  # Postgres
  postgres:
    container_name: postgres
    # image: dpage/pgadmin4
    # build: /postgres
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${herokuUser}
      - POSTGRES_PASSWORD=${herokuDbPassword}
      - POSTGRES_DB=${herokuDatabase}
      - POSRGRES_HOST=${herokuHost}
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=Piper007!
      # - POSTGRES_DB=postgres
      # - POSRGRES_HOST=localhost
      # - PGADMIN_DEFAULT_EMAIL=cabiediger@gmail.com
      # - PGADMIN_DEFAULT_PASSWORD=Piper007!
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
